# Generated by Django 4.0.4 on 2022-04-19 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='No inscrito el nombre ', max_length=255)),
                ('creador_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='No inscrito el nombre ', max_length=255)),
                ('creador_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('hora_registro', models.TimeField(blank=True, null=True)),
                ('unidad', models.IntegerField(default=0)),
                ('movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Movimiento no seleccionado', max_length=255)),
                ('cantidad', models.IntegerField(default=0)),
                ('horometro', models.CharField(default='', max_length=255)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.asignacion')),
                ('creador_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.item')),
            ],
        ),
    ]
