# Generated by Django 4.0.4 on 2022-04-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_salida_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='hora_registro',
        ),
    ]
