# Generated by Django 4.0.4 on 2022-04-22 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_entrada_hora_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha',
            new_name='fecha_entrada',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='fecha',
            new_name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='hora_registro',
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 4, 21, 20, 12, 3, 769322), null=None),
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 4, 21, 20, 12, 3, 769322), null=None),
        ),
    ]
