# Generated by Django 4.0.4 on 2022-04-27 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_rename_fecha_salida_registro_stock_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 4, 26, 23, 45, 38, 528825), null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 4, 26, 23, 45, 38, 528825), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 4, 26, 23, 45, 38, 529822), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 4, 26, 23, 45, 38, 529822), null=None),
        ),
    ]
