# Generated by Django 4.0.4 on 2022-05-03 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_item_unidad_alter_entrada_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 19, 44, 608061), null=None),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='horometro',
            field=models.CharField(default='x', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 19, 44, 607063), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 19, 44, 608061), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='horometro',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 19, 44, 608061), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horometro',
            field=models.FloatField(default=0.0),
        ),
    ]
