# Generated by Django 4.0.4 on 2022-05-03 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_entrada_fecha_registro_alter_entrada_horometro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_stock',
            name='horometro_imagen',
            field =  models.ImageField(upload_to='Horometro/%Y/%m/%d', null=False, blank=False , default='Horometro/blank.png'),
        ),
        migrations.AddField(
            model_name='salida',
            name='horometro_imagen',
            field=models.ImageField(default='Horometro/blank.png', upload_to='Horometro/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 40, 10, 468394), null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 40, 10, 467397), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 40, 10, 469391), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 2, 20, 40, 10, 468394), null=None),
        ),
    ]
