# Generated by Django 4.0.4 on 2022-05-06 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_frente_alter_entrada_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_stock',
            name='frente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.frente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salida',
            name='frente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='client.frente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 6, 9, 5, 57, 77377), null=None),
        ),
        migrations.AlterField(
            model_name='frente',
            name='nombre',
            field=models.CharField(default='x', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 6, 9, 5, 57, 77377), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 6, 9, 5, 57, 78375), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 6, 9, 5, 57, 78375), null=None),
        ),
    ]
