# Generated by Django 4.0.4 on 2022-05-16 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_entrada_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 16, 11, 35, 18, 259088), null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 16, 11, 35, 18, 259088), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 16, 11, 35, 18, 259088), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 16, 11, 35, 18, 259088), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='movimiento',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], default='Movimiento no seleccionado', max_length=255),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 16, 11, 35, 18, 259088), null=None),
        ),
    ]
