# Generated by Django 4.0.4 on 2022-05-31 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_alter_entrada_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_stock',
            name='upload',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 19, 53, 606251), null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 19, 53, 605254), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 19, 53, 607248), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 19, 53, 607248), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 19, 53, 606251), null=None),
        ),
    ]
