# Generated by Django 4.0.4 on 2022-05-31 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_registro_stock_upload_alter_entrada_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_stock',
            name='upload',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 24, 18, 848724), null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 24, 18, 847726), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 24, 18, 849721), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 24, 18, 849721), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 5, 24, 18, 848724), null=None),
        ),
    ]
