# Generated by Django 4.0.4 on 2022-05-31 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_alter_entrada_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 12, 2, 39, 759131), null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_ultimo_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 12, 2, 39, 758133), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 12, 2, 39, 760129), null=None),
        ),
        migrations.AlterField(
            model_name='registro_stock',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 12, 2, 39, 760129), null=None),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_registro',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 5, 31, 12, 2, 39, 759131), null=None),
        ),
    ]
